[package]
cairo-version = "2.2.0"
name = "dojo_examples"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# IMPORTANT: Dojo should be pinned to a specific version or else your world might not compile
dojo = { git = "https://github.com/dojoengine/dojo", rev="v0.3.2" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# local katana devnet
rpc_url = "http://localhost:5050/"

# account address of world deployer
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"

# private key of world deployer
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# world contract address
world_address = "0x789c94ef39aeebc7f8c4c4633030faefb8bee454e358ae53d06ced36136d7d6"
    